version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ege_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 3s
      timeout: 3s
      retries: 5

  api:
    build: ./api
    container_name: ege_api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: >
      bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

  bot:
    build: ./bot
    container_name: ege_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - api
    command: python bot.py

volumes:
  postgres_data:
